version: '3.3'

services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    privileged: true
    volumes:
      - ./backend:/home/backen

#  frontend:
#    container_name: frontend
#    build: ./frontend
#    restart: always
#  nginx: 
#    build: ./nginx
#    container_name: nginx
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      - analyser
#      - source-viewer
#      - frontend
#    restart: always